"""Identify a Skynet Desktop build by its CONTENT, not just its version string.

Why this exists (live defect, 2026-08-07): two different payloads both called themselves
0.1.1 -- the installed app carried app.asar c13382ec (379,694 bytes) while the freshly built
installer carried 6bf1ba06 (380,102 bytes), built 2h46m apart. Same version number, different
code. A crash report saying "0.1.1" was therefore untriageable. CDP advisor (Gemini 3.6
Thinking, 2026-08-07) ranked this a BLOCKER and prescribed embedding build metadata plus
strict version immutability.

The load-bearing idea is `source_digest`: a sha256 over the exact reviewed source members that
go into app.asar. It identifies the payload whether or not the working tree is committed, so
two distinct builds can NEVER collide on a build id -- which a git commit SHA alone cannot
guarantee, because a dirty tree does not determine its own bytes. The commit SHA is recorded as
PROVENANCE (where the bytes claim to come from), and `source_members_clean` states honestly
whether that claim is verifiable.

That distinction is what lets release approval move upstream off the 99.7MB wrapper blob:
approve reviewable source, bind it by digest, derive the installer hash mechanically.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path
from typing import Any, Callable, Iterable

ROOT = Path(__file__).resolve().parent.parent
DESKTOP_ROOT = ROOT / "desktop"
ATTESTATION_PATH = DESKTOP_ROOT / "release-build-attestation.json"
SCHEMA = "skynet_desktop_build_attestation/1"

# The exact members that make up the reviewed payload. Kept identical to the release gate's
# SOURCE_MEMBERS -- verified by test, not by hope, so the two cannot drift apart.
SOURCE_MEMBERS = (
    "main.js",
    "preload.js",
    "lib/cli_provisioning.js",
    "lib/portable_runtime.js",
    "lib/sidecar_runtime.js",
    "renderer/index.html",
    "renderer/app.js",
    "renderer/app.css",
    "build/icon.ico",
    "build/icon.png",
)

_HEX40 = re.compile(r"^[0-9a-f]{40}$")


def _sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def compute_source_digest(source_root: Path = DESKTOP_ROOT) -> tuple[str, dict[str, str]]:
    """Hash the reviewed payload members into one content identity.

    The digest covers the member NAME as well as its bytes, so swapping two files' contents
    changes the digest. Members are processed in a fixed order; a missing member is an error
    rather than a silently shorter digest, which would let a payload lose a file unnoticed.
    """
    per_member: dict[str, str] = {}
    outer = hashlib.sha256()
    for member in SOURCE_MEMBERS:
        path = source_root / Path(member)
        if not path.is_file():
            raise RuntimeError(f"reviewed source member is missing: {member}")
        member_hash = _sha256_file(path)
        per_member[member] = member_hash
        outer.update(member.encode("utf-8"))
        outer.update(b"\0")
        outer.update(member_hash.encode("ascii"))
        outer.update(b"\0")
    return outer.hexdigest(), per_member


def compute_wrapper_config_digest(
    package: dict[str, Any], source_root: Path = DESKTOP_ROOT
) -> tuple[str, dict[str, Any]]:
    """Hash everything that determines what the NSIS WRAPPER does.

    This is the piece a reviewer could not previously check without the 99.7MB binary. The
    wrapper's behaviour is not arbitrary: it is generated by electron-builder from the
    declarative `build` config plus any `nsis.include` script. Hashing both makes that
    behaviour reviewable as a few KB of text, so approval can bind THIS instead of the blob.

    Any include file that is declared but missing is a hard error -- silently digesting a
    smaller input would let a script vanish from review while the digest still "matched".
    """
    build_config = package.get("build")
    if not isinstance(build_config, dict):
        raise RuntimeError("package.json has no build config")
    canonical = json.dumps(build_config, sort_keys=True, separators=(",", ":"))
    outer = hashlib.sha256()
    outer.update(canonical.encode("utf-8"))
    outer.update(b"\0")

    includes: dict[str, str] = {}
    nsis = build_config.get("nsis") if isinstance(build_config.get("nsis"), dict) else {}
    declared = nsis.get("include")
    candidates = [declared] if isinstance(declared, str) else list(declared or [])
    for relative in sorted(candidates):
        path = source_root / Path(str(relative))
        if not path.is_file():
            raise RuntimeError(f"declared nsis include is missing: {relative}")
        include_hash = _sha256_file(path)
        includes[str(relative)] = include_hash
        outer.update(str(relative).encode("utf-8"))
        outer.update(b"\0")
        outer.update(include_hash.encode("ascii"))
        outer.update(b"\0")
    return outer.hexdigest(), {"buildConfigSha256": hashlib.sha256(canonical.encode("utf-8")).hexdigest(), "nsisIncludes": includes}


def _git(args: list[str], repo_root: Path) -> str:
    result = subprocess.run(
        ["git", *args],
        cwd=str(repo_root),
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {result.stderr.strip()[:200]}")
    return result.stdout.strip()


def git_provenance(repo_root: Path = ROOT, runner: Callable[[list[str], Path], str] = _git) -> dict[str, Any]:
    """Where the bytes CLAIM to come from, plus whether that claim is checkable.

    A dirty working tree is reported, never hidden: if the reviewed members differ from HEAD,
    the commit SHA does not identify the payload and must not be treated as if it did.
    """
    try:
        commit = runner(["rev-parse", "HEAD"], repo_root)
    except Exception as exc:
        return {"commit": None, "source_members_clean": False, "detail": str(exc)[:200]}
    if not _HEX40.match(commit):
        return {"commit": None, "source_members_clean": False, "detail": "HEAD is not a 40-hex commit"}
    member_paths = [f"desktop/{member}" for member in SOURCE_MEMBERS]
    try:
        # TRACKING is checked first and separately. `git status --porcelain -- <path>` prints
        # NOTHING for a path that is untracked-and-ignored, so relying on status alone reported
        # desktop/ -- which is gitignored in this repo -- as CLEAN while no member was committed
        # at all. That is the worst possible answer: the commit would appear to vouch for bytes
        # git has never seen. An untracked member is unclean, full stop.
        tracked = {line.strip() for line in runner(["ls-files", "--", *member_paths], repo_root).splitlines() if line.strip()}
        dirty = runner(["status", "--porcelain", "--", *member_paths], repo_root)
    except Exception as exc:
        # Unknown is not clean. Refusing to guess here is the whole point.
        return {"commit": commit, "source_members_clean": False, "detail": str(exc)[:200]}
    untracked = sorted(path for path in member_paths if path not in tracked)
    modified = sorted({line[3:].strip() for line in dirty.splitlines() if line.strip()})
    changed = sorted(set(untracked) | set(modified))
    return {
        "commit": commit,
        "source_members_clean": not changed,
        "dirty_members": changed,
        "untracked_members": untracked,
    }


def build_id(version: str, source_digest: str, provenance: dict[str, Any]) -> str:
    """A build id that is UNIQUE PER PAYLOAD.

    Clean tree  -> 0.1.1+g<short-commit>.<short-digest>
    Dirty tree  -> 0.1.1+dirty.<short-digest>
    The source digest is present in BOTH forms, so two builds can never share an id even when
    the commit is identical or absent. SemVer build metadata (after '+') is the right home for
    this: it does not affect version precedence.
    """
    short_digest = source_digest[:12]
    commit = provenance.get("commit")
    if provenance.get("source_members_clean") and isinstance(commit, str):
        return f"{version}+g{commit[:8]}.{short_digest}"
    return f"{version}+dirty.{short_digest}"


def compute_stamp(
    package: dict[str, Any],
    source_root: Path = DESKTOP_ROOT,
    repo_root: Path = ROOT,
    provenance_reader: Callable[..., dict[str, Any]] | None = None,
) -> dict[str, Any]:
    version = str(package.get("version") or "")
    if not version:
        raise RuntimeError("package.json has no version")
    release = package.get("skynetRelease") if isinstance(package.get("skynetRelease"), dict) else {}
    source_digest, members = compute_source_digest(source_root)
    wrapper_digest, wrapper_detail = compute_wrapper_config_digest(package, source_root)
    provenance = (provenance_reader or git_provenance)(repo_root)
    identifier = build_id(version, source_digest, provenance)
    return {
        "schema": SCHEMA,
        "productName": "Skynet Desktop",
        "version": version,
        "distributionMode": release.get("distributionMode"),
        "buildId": identifier,
        "sourceDigest": source_digest,
        "sourceMembers": members,
        "wrapperConfigDigest": wrapper_digest,
        "wrapperConfig": wrapper_detail,
        "sourceCommit": provenance.get("commit"),
        "sourceMembersClean": bool(provenance.get("source_members_clean")),
        "dirtyMembers": provenance.get("dirty_members", []),
        "electronVersion": release.get("electronVersion"),
        "electronBuilderVersion": release.get("electronBuilderVersion"),
    }


RELEASE_ARCH = "x64"


def installer_name(
    version: str, distribution_mode: str | None = None, identifier: str | None = None
) -> str:
    """The public download name: `Skynet-Desktop-Setup-0.1.1-x64.exe`.

    This is the filename a stranger sees in their browser's download bar, so it carries the
    product, the version and the architecture -- and nothing else. An earlier iteration leaked
    build plumbing into it ("-dirty.ec6441f5cb0d", "-unsigned"), which reads as a broken or
    untrustworthy artifact to anyone who did not build it themselves.

    Hyphens, not spaces: a spaced filename shows up as `Skynet%20Desktop%20Setup...` in every
    URL, breaks naive copy/paste into a shell, and is materially worse to search for.

    Traceability does NOT live in this name. The content-derived build id is baked into the
    packaged app.asar, recorded in release-build-attestation.json, and published as a SHA-256
    beside the download. Identifying BYTES is a hash's job; a filename's job is to be
    recognisable. Version immutability keeps the two consistent: never publish two different
    payloads under one version -- bump the version instead.

    `identifier` is still accepted (and ignored) so existing call sites keep working; it
    deliberately no longer decorates the public artifact.
    """
    return f"Skynet-Desktop-Setup-{version}-{RELEASE_ARCH}.exe"


def _load_package(source_root: Path) -> dict[str, Any]:
    return json.loads((source_root / "package.json").read_text(encoding="utf-8"))


def electron_builder_args(stamp: dict[str, Any]) -> list[str]:
    """CLI overrides that bake the stamp into the packaged app.

    extraMetadata lands in the app.asar's package.json, which the release gate already reads
    and which permits extra keys beyond the pinned identity fields -- so the build id travels
    INSIDE the shipped payload and can be recovered from the artifact alone.
    """
    name = installer_name(stamp["version"], stamp.get("distributionMode"), stamp["buildId"])
    return [
        f"-c.extraMetadata.skynetBuild.buildId={stamp['buildId']}",
        f"-c.extraMetadata.skynetBuild.sourceDigest={stamp['sourceDigest']}",
        f"-c.extraMetadata.skynetBuild.sourceCommit={stamp.get('sourceCommit') or ''}",
        f"-c.extraMetadata.skynetBuild.sourceMembersClean={str(bool(stamp.get('sourceMembersClean'))).lower()}",
        f"-c.nsis.artifactName={name}",
    ]


def main(argv: Iterable[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Compute the Skynet Desktop build stamp")
    parser.add_argument("--json", action="store_true", help="print the full stamp as JSON")
    parser.add_argument("--build-id", action="store_true", help="print only the build id")
    parser.add_argument("--installer-name", action="store_true", help="print only the artifact name")
    parser.add_argument(
        "--electron-builder-args",
        action="store_true",
        help="print the electron-builder CLI overrides, one per line",
    )
    parser.add_argument("--write-attestation", action="store_true", help=f"write {ATTESTATION_PATH.name}")
    parser.add_argument(
        "--write-allowlist",
        action="store_true",
        help="write the schema/2 source-bound allowlist (still requires a committed Rule 1 receipt)",
    )
    args = parser.parse_args(list(argv) if argv is not None else None)

    package = _load_package(DESKTOP_ROOT)
    stamp = compute_stamp(package)

    if args.build_id:
        print(stamp["buildId"])
    elif args.installer_name:
        print(installer_name(stamp["version"], stamp.get("distributionMode"), stamp["buildId"]))
    elif args.electron_builder_args:
        print("\n".join(electron_builder_args(stamp)))
    else:
        print(json.dumps(stamp, indent=2))

    if args.write_attestation:
        ATTESTATION_PATH.write_text(json.dumps(stamp, indent=2) + "\n", encoding="utf-8")
    if args.write_allowlist:
        # Writing this file is NOT self-approval: the gate additionally requires a COMMITTED
        # Rule 1 receipt bound to this file's own sha256. What changed is what a reviewer must
        # read to grant it -- two digests over ~300KB of reviewable source and config, instead
        # of a 99.7MB NSIS wrapper no channel can carry.
        allowlist = {
            "schema": "skynet_desktop_installer_allowlist/2",
            "productName": "Skynet Desktop",
            "version": stamp["version"],
            "distributionMode": stamp["distributionMode"],
            "installerName": installer_name(stamp["version"], stamp.get("distributionMode")),
            "sourceDigest": stamp["sourceDigest"],
            "wrapperConfigDigest": stamp["wrapperConfigDigest"],
        }
        allowlist_path = DESKTOP_ROOT / "release-installer-allowlist.json"
        allowlist_path.write_text(json.dumps(allowlist, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {allowlist_path} (sha256 {_sha256_file(allowlist_path)})", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
